In [ ]:
from sklearn.ensemble import StackingClassifier, StackingRegressor, BaggingRegressor, BaggingClassifier, GradientBoostingRegressor,GradientBoostingClassifier, RandomForestClassifier, RandomForestRegressor
from sklearn.svm import LinearSVC
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv("classification_preprocessed.csv") 

In [ ]:
df1.drop(df1.columns[0], axis = 1, inplace = True)
df1.head()

age  Medu  Fedu  guardian_  traveltime  studytime  failures  famrel  \
0   18     4     4          1           2          2         0       4   
1   17     1     1          0           1          2         0       5   
2   15     1     1          1           1          2         3       4   
3   15     4     2          1           1          3         0       3   
4   16     3     3          0           1          2         0       4   

   freetime  goout  ...  Fjob_  reason_  schoolsup_  famsup_  paid_  \
0         3      4  ...      4        0           1        0      0   
1         3      3  ...      2        0           0        1      0   
2         3      2  ...      2        2           1        0      1   
3         2      2  ...      3        1           0        1      1   
4         3      2  ...      2        1           0        1      1   

   activities_  nursery_  higher_  internet_  romantic_  
0            0         1        1          0          0  
1            0         0        1          1          0  
2            0         1        1          1          0  
3            1         1        1          1          1  
4            0         1        1          0          0  

[5 rows x 33 columns]

In [ ]:
df1.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          395 non-null    int64
 1   Medu         395 non-null    int64
 2   Fedu         395 non-null    int64
 3   guardian_    395 non-null    int64
 4   traveltime   395 non-null    int64
 5   studytime    395 non-null    int64
 6   failures     395 non-null    int64
 7   famrel       395 non-null    int64
 8   freetime     395 non-null    int64
 9   goout        395 non-null    int64
 10  Dalc         395 non-null    int64
 11  Walc         395 non-null    int64
 12  health       395 non-null    int64
 13  absences     395 non-null    int64
 14  G1           395 non-null    int64
 15  G2           395 non-null    int64
 16  G3           395 non-null    int64
 17  school_      395 non-null    int64
 18  sex_         395 non-null    int64
 19  address_     395 non-null    int64
 20  famsize_  

In [ ]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:, 13].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
clf = BaggingClassifier()
clf.fit(X_train, y_train)

BaggingClassifier()

In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[33  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
df = pd.DataFrame({'Употребление алкоголя по будням': y_test, 'Предсказание': y_pred})
df.head()

Употребление алкоголя по будням  Предсказание
0                                0             0
1                               10            10
2                                0             0
3                                6             6
4                                2             2

In [ ]:
df = pd.DataFrame({'Употребление алкоголя по будням': y_test, 'Предсказание': y_pred})
df.head()

Употребление алкоголя по будням  Предсказание
0                                0             0
1                               10            10
2                                0             0
3                                6             6
4                                2             2

In [ ]:
from sklearn.ensemble import BaggingRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[33  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
df = pd.DataFrame({'Употребление алкоголя по будням': y_test, 'Предсказание': y_pred})
df.head()

Употребление алкоголя по будням  Предсказание
0                                0             0
1                               10            10
2                                0             0
3                                6             6
4                                2             2

In [ ]:
df = pd.DataFrame({'Употребление алкоголя по будням': y_test, 'Предсказание': y_pred})
df.head()

Употребление алкоголя по будням  Предсказание
0                                0             0
1                               10            10
2                                0             0
3                                6             6
4                                2             2

In [ ]:
!pip install catboost
!pip install ipywidgets
from catboost import * 
from catboost import datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 1.3 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from catboost import CatBoostClassifier

model = CatBoostClassifier (task_type = "CPU",iterations = 200,learning_rate = 0.1,)
model.fit (X_train, y_train,)

y_pred = model.predict(X_test)
print(model.score(X_test, y_test))

0:	learn: 3.1688703	total: 76.8ms	remaining: 15.3s
1:	learn: 3.0248370	total: 100ms	remaining: 9.91s
2:	learn: 2.6707170	total: 122ms	remaining: 8.01s
3:	learn: 2.5186904	total: 144ms	remaining: 7.03s
4:	learn: 2.3853765	total: 165ms	remaining: 6.44s
5:	learn: 2.2523770	total: 187ms	remaining: 6.04s
6:	learn: 2.1565590	total: 208ms	remaining: 5.74s
7:	learn: 2.0913529	total: 229ms	remaining: 5.51s
8:	learn: 2.0065306	total: 251ms	remaining: 5.32s
9:	learn: 1.9052398	total: 272ms	remaining: 5.17s
10:	learn: 1.8489011	total: 298ms	remaining: 5.12s
11:	learn: 1.7834086	total: 320ms	remaining: 5.01s
12:	learn: 1.7181508	total: 341ms	remaining: 4.91s
13:	learn: 1.6425741	total: 362ms	remaining: 4.81s
14:	learn: 1.6069301	total: 384ms	remaining: 4.74s
15:	learn: 1.5759651	total: 406ms	remaining: 4.66s
16:	learn: 1.5492712	total: 431ms	remaining: 4.64s
17:	learn: 1.5049504	total: 456ms	remaining: 4.61s
18:	learn: 1.4561520	total: 478ms	remaining: 4.55s
19:	learn: 1.4370434	total: 503ms	remain