In [ ]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
df = load_iris()

In [ ]:
type(df)

sklearn.utils.Bunch

In [ ]:
X = df['data']
y = df["target"]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
clf = MLPClassifier()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


1.0

In [ ]:
y_pred = clf.predict(X_test)
df_compare = pd.DataFrame({'Что-то': y_test, 'Предсказание': y_pred})
df_compare.head(10)

Что-то  Предсказание
0       1             1
1       1             1
2       1             1
3       0             0
4       1             1
5       2             2
6       1             1
7       2             2
8       1             1
9       2             2

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix

clf = KNeighborsClassifier(n_neighbors=15)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 9  0  0]
 [ 0 14  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0


In [ ]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 9  0  0]
 [ 0 14  0]
 [ 0  1  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.93      1.00      0.97        14
           2       1.00      0.86      0.92         7

    accuracy                           0.97        30
   macro avg       0.98      0.95      0.96        30
weighted avg       0.97      0.97      0.97        30

0.9666666666666667


In [ ]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 9  0  0]
 [ 0 14  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0


In [ ]:
from sklearn import svm

clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 9  0  0]
 [ 0 14  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0


In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[ 9  0  0]
 [ 0 14  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         7

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0


In [ ]:
y = np.array([y])
I = np.concatenate((X, y.T), axis=1)
A = np.array([[-0.2, 0.3, -0.4, 0.1, -0.1], [0.1, -0.3, -0.4, -0.2, 0.1]]) #randomnые значения для первого слоя
B = np.array([0.2, 0.3]) #для второго

In [ ]:
def f(x): #сигмоидальная функция активации
  return 2 / (1 + np.exp(-2 * x)) - 1 #гиперболическая функция - гиперболический тангенс: точность 0.7
  #return 1 / (np.exp(x) + 1) логистическая функция - функция Ферми - экспоненциальная сигмоида: точность 0.3


def derivative(x):
  return (1 - x**2) / 2


def pogulyaem_po_neurosety(array):
  sum = np.dot(A, array)
  out = np.array([f(x) for x in sum])
  sum = np.dot(B, out)
  y = f(sum)
  return (y, out)
#запоминаем все выходные значения

def fit(I):
  lambd = 0.1 #шаг обучения
  for k in range(5000):
      x = I[np.random.randint(0, len(I))]  #выбираем любую строчку из сконкатенированного датасета ирис
      y, out = pogulyaem_po_neurosety(x[0:5]) #гуляем по нейросети и гуляем не зря: вычисляем выходные значения нейронов. y - выход на всей нейросети, out - на скрытых слоях
      e = y - x[-1]
      delta = e * derivative(y) #тут вычисляем локальный градиент: произведение ошибки на производную от выходного значения на всей нейросети
      B[0] -= lambd * delta * out[0] # корректировка веса первой связи
      B[1] -= lambd * delta * out[1] # корректировка веса второй связи
      delta2 = B * delta * derivative(out) # вектор из 2-х величин локальных градиентов
      # корректировка связей первого слоя:
      A[0, :] -= np.array(x[0:5]) * delta2[0] * lambd
      A[1, :] -= np.array(x[0:5]) * delta2[1] * lambd


def score(y, l_):
  k = 0
  for i in range(len(l_)):
    if y[0][i] == l_[i]:
      k += 1
  final_score = k / len(l_)
  return round(final_score, 1)


def dobavim():
  l_ = list()
  for x in I:
    y_, out = pogulyaem_po_neurosety(x[0:5])
    l_.append(round(y_))
  l_ = np.array(l_)
  l_.astype(np.int64)
  return l_

In [ ]:
fit(I)
print(score(y, dobavim()))

0.7


In [ ]:
df = pd.read_csv("train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.drop(['PassengerId', 'Name', 'Ticket', "Cabin"], axis=1, inplace=True)
df.fillna(df.mean(), inplace=True)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
df = pd.get_dummies(data=df, prefix='', columns=['Sex', 'Embarked'])
df

Survived  Pclass        Age  SibSp  Parch     Fare  _female  _male  _C  \
0           0       3  22.000000      1      0   7.2500        0      1   0   
1           1       1  38.000000      1      0  71.2833        1      0   1   
2           1       3  26.000000      0      0   7.9250        1      0   0   
3           1       1  35.000000      1      0  53.1000        1      0   0   
4           0       3  35.000000      0      0   8.0500        0      1   0   
..        ...     ...        ...    ...    ...      ...      ...    ...  ..   
886         0       2  27.000000      0      0  13.0000        0      1   0   
887         1       1  19.000000      0      0  30.0000        1      0   0   
888         0       3  29.699118      1      2  23.4500        1      0   0   
889         1       1  26.000000      0      0  30.0000        0      1   1   
890         0       3  32.000000      0      0   7.7500        0      1   0   

     _Q  _S  
0     0   1  
1     0   0  
2     0   1  
3     0   1  
4     0   1  
..   ..  ..  
886   0   1  
887   0   1  
888   0   1  
889   0   0  
890   1   0  

[891 rows x 11 columns]

In [ ]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
clf = KNeighborsClassifier(n_neighbors=15)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[127  21]
 [ 38  37]]
              precision    recall  f1-score   support

           0       0.77      0.86      0.81       148
           1       0.64      0.49      0.56        75

    accuracy                           0.74       223
   macro avg       0.70      0.68      0.68       223
weighted avg       0.73      0.74      0.73       223

0.7354260089686099


In [ ]:
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[123  25]
 [ 17  58]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       148
           1       0.70      0.77      0.73        75

    accuracy                           0.81       223
   macro avg       0.79      0.80      0.79       223
weighted avg       0.82      0.81      0.81       223

0.8116591928251121


In [ ]:
clf = MLPClassifier()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.8295964125560538

In [ ]:
y = np.array([y])
I = np.concatenate((X, y.T), axis=1)

In [ ]:
fit(I)
print(score(y, dobavim()))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


0.6


In [ ]:
#task2
df = pd.read_csv("classification_preprocessed.csv")

In [ ]:
df.drop(df.columns[0], axis = 1, inplace = True)
df.head()

age  Medu  Fedu  guardian_  traveltime  studytime  failures  famrel  \
0   18     4     4          1           2          2         0       4   
1   17     1     1          0           1          2         0       5   
2   15     1     1          1           1          2         3       4   
3   15     4     2          1           1          3         0       3   
4   16     3     3          0           1          2         0       4   

   freetime  goout  ...  Fjob_  reason_  schoolsup_  famsup_  paid_  \
0         3      4  ...      4        0           1        0      0   
1         3      3  ...      2        0           0        1      0   
2         3      2  ...      2        2           1        0      1   
3         2      2  ...      3        1           0        1      1   
4         3      2  ...      2        1           0        1      1   

   activities_  nursery_  higher_  internet_  romantic_  
0            0         1        1          0          0  
1            0         0        1          1          0  
2            0         1        1          1          0  
3            1         1        1          1          1  
4            0         1        1          0          0  

[5 rows x 33 columns]

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 13].values

In [ ]:
y = np.array([y])
I = np.concatenate((X, y.T), axis=1)

In [ ]:
fit(I)
print(score(y, dobavim()))

0.0


In [ ]:
df = pd.read_csv("regression_preprocessed.csv")

In [ ]:
df.drop(df.columns[0], axis = 1, inplace = True)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 13].values

In [ ]:
y = np.array([y])
I = np.concatenate((X, y.T), axis=1)

In [ ]:
fit(I)
print(score(y, dobavim()))

0.0
