In [1]:
from sklearn.ensemble import StackingClassifier, StackingRegressor, BaggingRegressor, BaggingClassifier, GradientBoostingRegressor,GradientBoostingClassifier, RandomForestClassifier, RandomForestRegressor
from sklearn.svm import LinearSVC
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("C:/Users/User/data/student-mat.csv") 

In [3]:
df1.drop(df1.columns[0], axis = 1, inplace = True)
df1.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... famrel  freetime  goout  Dalc Walc health absences  G1  G2  G3  
0  ...      4         3      4     1    1      3        6   5   6   6  
1  ...      5         3      3     1    1      3        4   5   5   6  
2  ...      4         3      2     2    3      3       10   7   8  10  
3  ...      3         2      2     1    1      5        2  15  14  15  
4  ...      4         3      2     1    2      5        4   6  10  10  

[5 rows x 32 columns]

In [4]:
df1.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   sex         395 non-null    object
 1   age         395 non-null    int64 
 2   address     395 non-null    object
 3   famsize     395 non-null    object
 4   Pstatus     395 non-null    object
 5   Medu        395 non-null    int64 
 6   Fedu        395 non-null    int64 
 7   Mjob        395 non-null    object
 8   Fjob        395 non-null    object
 9   reason      395 non-null    object
 10  guardian    395 non-null    object
 11  traveltime  395 non-null    int64 
 12  studytime   395 non-null    int64 
 13  failures    395 non-null    int64 
 14  schoolsup   395 non-null    object
 15  famsup      395 non-null    object
 16  paid        395 non-null    object
 17  activities  395 non-null    object
 18  nursery     395 non-null    object
 19  higher      395 non-null    object
 20  internet  

In [5]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:, 13].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: 'F'

In [8]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [9]:
clf = BaggingClassifier()
clf.fit(X_train, y_train)

ValueError: could not convert string to float: 'F'

In [10]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

[[80  0  0  0]
 [10  0  0  0]
 [ 5  0  0  0]
 [ 4  0  0  0]]
              precision    recall  f1-score   support

           0       0.81      1.00      0.89        80
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         4

    accuracy                           0.81        99
   macro avg       0.20      0.25      0.22        99
weighted avg       0.65      0.81      0.72        99

0.8080808080808081


C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
df = pd.DataFrame({'Пожар': y_test, 'Предсказание': y_pred})
df.head()

Пожар  Предсказание
0      1             0
1      0             0
2      0             0
3      0             0
4      2             0

In [12]:
df = pd.DataFrame({'Пожар': y_test, 'Предсказание': y_pred})
df.head()

Пожар  Предсказание
0      1             0
1      0             0
2      0             0
3      0             0
4      2             0

In [13]:
from sklearn.ensemble import BaggingRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [14]:
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(X_, y_, test_size=0.25)

NameError: name 'X_' is not defined

In [15]:
from sklearn.model_selection import learning_curve 
from sklearn.metrics import make_scorer
from sklearn.linear_model import Lasso, Ridge, LassoCV, LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

reg = BaggingRegressor()
reg.fit(X_reg_train, y_reg_train)
y_reg_pred = reg.predict(X_reg_test)
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

NameError: name 'X_reg_train' is not defined

In [16]:
df=pd.DataFrame({'Индекс пожара': y_reg_test, 'Предсказание': y_reg_pred})
df.head()

NameError: name 'y_reg_test' is not defined

In [17]:
from sklearn.ensemble import GradientBoostingClassifier

In [18]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

ValueError: could not convert string to float: 'F'

In [19]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

ValueError: could not convert string to float: 'M'

In [20]:
df = pd.DataFrame({'Пожар': y_test, 'Предсказание': y_pred})
df.head()

Пожар  Предсказание
0      1             0
1      0             0
2      0             0
3      0             0
4      2             0

In [21]:
from sklearn.ensemble import GradientBoostingRegressor

In [22]:
df=pd.DataFrame({'Индекс пожара': y_reg_test, 'Предсказание': y_reg_pred})
df.head()

NameError: name 'y_reg_test' is not defined

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.pipeline import make_pipeline

In [24]:
base_learners = [
                 ('rf_1', RandomForestClassifier(n_estimators=10, random_state=42)),
                 ('rf_2', LogisticRegression())             
                ]
clf = StackingClassifier(estimators=base_learners,
                         final_estimator=LogisticRegression(),  
                         cv=10)
clf.fit(X_train, y_train)

ValueError: could not convert string to float: 'F'

In [25]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(clf.score(X_test, y_test))

AttributeError: 'StackingClassifier' object has no attribute 'estimators_'

In [26]:
df = pd.DataFrame({'Пожар': y_test, 'Предсказание': y_pred})
df.head()

Пожар  Предсказание
0      1             0
1      0             0
2      0             0
3      0             0
4      2             0

In [27]:
from sklearn.ensemble import StackingRegressor

In [28]:
base_learners = [
    ('rf', RandomForestRegressor(n_estimators=10, random_state=42)),
    ('svr', make_pipeline(StandardScaler(), LinearRegression()))]

clf = StackingRegressor(estimators = base_learners)
clf.fit(X_reg_train, y_reg_train)
y_reg_pred = reg.predict(X_reg_test)
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

NameError: name 'X_reg_train' is not defined

In [29]:
df=pd.DataFrame({'Индекс пожара': y_reg_test, 'Предсказание': y_reg_pred})
df.head()

NameError: name 'y_reg_test' is not defined

In [30]:
!pip install catboost
!pip install ipywidgets
from catboost import * 
from catboost import datasets

In [31]:
from catboost import CatBoostClassifier

model = CatBoostClassifier (
    task_type = "CPU",
    iterations = 200,
    learning_rate = 0.1,
    use_best_model = True,
    loss_function = "CrossEntropy"
)

model.fit (
    X_train, y_train,
    eval_set = (X_test, y_test),
    verbose = 30,
    plot = True
)

y_pred = model.predict(X_test)
print(model.score(X_test, y_test))

CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=0]="F": Cannot convert 'b'F'' to float

In [33]:
from catboost import CatBoostRegressor

model = CatBoostRegressor (
    task_type = "CPU",
    learning_rate = 0.1,
    use_best_model = True,
    loss_function = "RMSE"
)

model.fit (
    X_reg_train, y_reg_train,
    eval_set = (X_reg_test, y_reg_test),
    verbose = False,
    plot = True
)

y_reg_pred = model.predict(X_reg_test)
print(model.score(X_reg_test, y_reg_test))

NameError: name 'X_reg_train' is not defined

In [34]:
MSE = mean_squared_error(y_reg_test, y_reg_pred) 
print("MSE: ", MSE)
print("RMSE:", np.sqrt(MSE))
MAE = mean_absolute_error(y_reg_test, y_reg_pred)
print("MAE: ", MAE)
print("R2: ", r2_score(y_reg_test, y_reg_pred))

NameError: name 'y_reg_test' is not defined